<?php
/**
 * Created by PhpStorm.
 * User: unasus
 * Date: 6/27/18
 * Time: 9:09 AM
 */

namespace AppBundle\Repository;

/**
 * TbProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbProductRepository extends \Doctrine\ORM\EntityRepository
{

}