<?php

namespace AppBundle\Repository;

/**
 * TbUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TbUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
