<?php
/**
 * Created by PhpStorm.
 * User: unasus
 * Date: 6/27/18
 * Time: 9:35 AM
 */

namespace AppBundle\Form;


use AppBundle\Entity\TbProduct;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\CallbackTransformer;
use Symfony\Component\Form\Extension\Core\Type\CurrencyType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TbProductType extends AbstractType
{

    /**
     * {@inheritdoc}
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
        $builder->add('name', TextType::class, array(
            'label' => 'Name',
            'attr' => array()
        ));
        $builder->add('value', CurrencyType::class, array(
            'label' => 'Value',
            'attr' => array('currency' => 'BRL')
        ))->addModelTransformer(new CallbackTransformer(
            function ($product) {
                $product->setValue(floatval($product->getValue()));
                return $product;
            },
            function ($product) {
                return $product;
            }
        ));
    }

    /**
     * {@inheritdoc}
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\TbProduct',
            'csrf_protection' => false,
            'allow_extra_fields' => true,
        ));
    }

    public function getBlockPrefix()
    {
        return 'product';
    }
}